#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DCOP-Amarok-Playlist
version:      0.004
version_from: Playlist.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
